import { recipe } from "./catalogHelpers";

export const BASE_RECIPES = [
  recipe("old-fashioned","Old Fashioned","cocktail","A classic whiskey cocktail built around spirit, sugar, and bitters.","Add bourbon, simple syrup, and bitters to a rocks glass with ice. Stir until chilled. Garnish with orange peel.","IBA reference","https://iba-world.com/cocktails/",[["Bourbon",2,"oz",false],["Simple Syrup",0.25,"oz",false],["Angostura Bitters",2,"dash",false],["Orange Peel",1,"pc",true]]),
  recipe("manhattan","Manhattan","cocktail","Whiskey, sweet vermouth, and bitters.","Stir whiskey, sweet vermouth, and bitters with ice until chilled, then strain into a chilled glass.","IBA reference","https://iba-world.com/cocktails/",[["Rye Whiskey",2,"oz",false],["Sweet Vermouth",1,"oz",false],["Angostura Bitters",2,"dash",false]]),
  recipe("margarita","Margarita","cocktail","A tequila sour with orange liqueur and lime.","Shake tequila, triple sec, and lime juice with ice. Strain into a chilled glass, optionally with a salted rim.","IBA reference","https://iba-world.com/cocktails/",[["Blanco Tequila",2,"oz",false],["Triple Sec",1,"oz",false],["Lime Juice",1,"oz",false],["Salt",1,"tsp",true]]),
  recipe("daiquiri","Daiquiri","cocktail","A simple rum sour with lime and sugar.","Shake white rum, lime juice, and simple syrup with ice, then strain into a chilled glass.","IBA reference","https://iba-world.com/cocktails/",[["White Rum",2,"oz",false],["Lime Juice",1,"oz",false],["Simple Syrup",0.75,"oz",false]]),
  recipe("gin-tonic","Gin and Tonic","cocktail","Gin lengthened with tonic water.","Build gin and tonic water over ice in a highball glass. Stir gently.","Open classic reference","https://en.wikibooks.org/wiki/Bartending/Cocktails",[["Gin",2,"oz",false],["Tonic Water",4,"oz",false],["Lime Wedge",1,"pc",true]]),
  recipe("moscow-mule","Moscow Mule","cocktail","Vodka, ginger beer, and lime.","Build vodka and lime juice over ice, top with ginger beer, and stir gently.","Open classic reference","https://en.wikibooks.org/wiki/Bartending/Cocktails",[["Vodka",2,"oz",false],["Ginger Beer",4,"oz",false],["Lime Juice",0.5,"oz",false]]),
  recipe("virgin-moscow-mule","Virgin Moscow Mule","mocktail","A non-alcoholic mule-style drink with ginger beer and lime.","Build lime juice over ice, top with ginger beer and club soda, then stir gently.","Virtual Bartender curated mocktail","local://virtual-bartender/curated",[["Ginger Beer",4,"oz",false],["Lime Juice",0.75,"oz",false],["Club Soda",1,"oz",false]],"moscow-mule"),
  recipe("whiskey-ginger","Whiskey Ginger","cocktail","Whiskey topped with ginger ale.","Build whiskey and ginger ale over ice and stir gently.","Virtual Bartender curated highball","local://virtual-bartender/curated",[["Bourbon",2,"oz",false],["Ginger Ale",4,"oz",false]]),
  recipe("rum-sprite","Rum and Sprite","cocktail","A simple rum highball with lemon-lime soda.","Build rum and Sprite over ice and stir gently.","Virtual Bartender curated highball","local://virtual-bartender/curated",[["White Rum",2,"oz",false],["Sprite",4,"oz",false]]),
  recipe("tequila-tonic","Tequila Tonic","cocktail","Tequila and tonic water over ice.","Build tequila and tonic water over ice and stir gently.","Virtual Bartender curated highball","local://virtual-bartender/curated",[["Blanco Tequila",2,"oz",false],["Tonic Water",4,"oz",false],["Lime Wedge",1,"pc",true]])
];
