import { recipe } from "./catalogHelpers";
const C="Virtual Bartender curated highball", L="local://virtual-bartender/curated";
const high=(key:string,name:string,a:string,b:string)=>recipe(key,name,"cocktail",`${name} over ice.`,`Build ${a.toLowerCase()} and ${b.toLowerCase()} over ice and stir gently.`,C,L,[[a,2,"oz",false],[b,4,"oz",false]]);
export const RECIPES_V4 = [
 high("vodka-soda","Vodka Soda","Vodka","Club Soda"), high("gin-soda","Gin Soda","Gin","Club Soda"),
 recipe("tequila-soda","Tequila Soda","cocktail","Tequila with soda and lime.","Build tequila and lime over ice, top with club soda, and stir gently.",C,L,[["Blanco Tequila",2,"oz",false],["Club Soda",4,"oz",false],["Lime Juice",0.5,"oz",false]]),
 high("bourbon-soda","Bourbon Soda","Bourbon","Club Soda"), high("rum-tonic","Rum Tonic","White Rum","Tonic Water"), high("gin-ginger","Gin Ginger","Gin","Ginger Ale"), high("vodka-ginger","Vodka Ginger","Vodka","Ginger Ale"), high("tequila-ginger","Tequila Ginger","Blanco Tequila","Ginger Ale"), high("rum-ginger","Rum Ginger","White Rum","Ginger Ale"), high("bourbon-tonic","Bourbon Tonic","Bourbon","Tonic Water"), high("whiskey-cola","Whiskey Cola","Rye Whiskey","Cola"), high("rum-root-beer","Rum and Root Beer","Dark Rum","Root Beer"), high("bourbon-root-beer","Bourbon and Root Beer","Bourbon","Root Beer"), high("gin-grapefruit","Gin Grapefruit","Gin","Grapefruit Juice"), high("tequila-grapefruit","Tequila Grapefruit","Blanco Tequila","Grapefruit Juice"), high("rum-pineapple","Rum Pineapple","White Rum","Pineapple Juice"), high("vodka-pineapple","Vodka Pineapple","Vodka","Pineapple Juice"), high("tequila-pineapple","Tequila Pineapple","Blanco Tequila","Pineapple Juice"), high("rum-orange","Rum Orange","White Rum","Orange Juice"), high("gin-orange","Gin Orange","Gin","Orange Juice"), high("tequila-orange","Tequila Orange","Blanco Tequila","Orange Juice"), high("vodka-cranberry","Vodka Cranberry","Vodka","Cranberry Juice"), high("gin-cranberry","Gin Cranberry","Gin","Cranberry Juice"), high("tequila-cranberry","Tequila Cranberry","Blanco Tequila","Cranberry Juice"), high("rum-cranberry","Rum Cranberry","White Rum","Cranberry Juice"),
 ...[["bourbon-lemonade","Bourbon Lemonade","Bourbon"],["vodka-lemonade","Vodka Lemonade","Vodka"],["gin-lemonade","Gin Lemonade","Gin"],["tequila-lemonade","Tequila Lemonade","Blanco Tequila"],["rum-lemonade","Rum Lemonade","White Rum"]].map(([k,n,s])=>recipe(k,n,"cocktail",`${n} with lemon, syrup, and soda.`,`Build ${s.toLowerCase()}, lemon, and syrup over ice, top with club soda, and stir.`,C,L,[[s,2,"oz",false],["Lemon Juice",1,"oz",false],["Simple Syrup",0.75,"oz",false],["Club Soda",3,"oz",false]])),
 recipe("bourbon-sour-no-egg","Bourbon Sour","cocktail","A straightforward bourbon sour without egg white.","Shake bourbon, lemon juice, and syrup with ice, then strain over fresh ice.","Virtual Bartender curated classic",L,[["Bourbon",2,"oz",false],["Lemon Juice",0.75,"oz",false],["Simple Syrup",0.75,"oz",false]]),
 ...[["gin-sour","Gin Sour","Gin"],["vodka-sour","Vodka Sour","Vodka"],["tequila-sour","Tequila Sour","Blanco Tequila"],["rum-sour","Rum Sour","White Rum"],["brandy-sour","Brandy Sour","Brandy"]].map(([k,n,s])=>recipe(k,n,"cocktail",`A ${s.toLowerCase()} sour with lemon and syrup.`,`Shake ${s.toLowerCase()}, lemon juice, and syrup with ice, then strain.`,"Virtual Bartender curated classic",L,[[s,2,"oz",false],["Lemon Juice",0.75,"oz",false],["Simple Syrup",0.75,"oz",false]])),
 recipe("amaretto-coffee","Amaretto Coffee","cocktail","Hot coffee with amaretto.","Combine hot coffee and amaretto in a mug and stir.","Virtual Bartender curated hot drink",L,[["Coffee",4,"oz",false],["Amaretto",1.5,"oz",false],["Cream",1,"oz",true]]),
 recipe("irish-creamless-coffee","Whiskey Coffee","cocktail","Coffee with whiskey and optional syrup.","Combine hot coffee and whiskey in a mug; sweeten if desired.","Virtual Bartender curated hot drink",L,[["Coffee",4,"oz",false],["Irish Whiskey",1.5,"oz",false],["Simple Syrup",0.5,"oz",true]]),
 ...[["coffee-cognac","Coffee and Cognac","Cognac"],["coffee-rum","Rum Coffee","Dark Rum"],["coffee-bourbon","Bourbon Coffee","Bourbon"]].map(([k,n,s])=>recipe(k,n,"cocktail",`Hot coffee with ${s.toLowerCase()}.`,`Combine hot coffee and ${s.toLowerCase()} in a mug and stir.`,"Virtual Bartender curated hot drink",L,[["Coffee",4,"oz",false],[s,1.5,"oz",false]])),
 recipe("orange-fizz-mocktail","Orange Fizz","mocktail","Orange juice and soda with a touch of syrup.","Build orange juice and syrup over ice, top with club soda, and stir.","Virtual Bartender curated mocktail",L,[["Orange Juice",3,"oz",false],["Simple Syrup",0.5,"oz",false],["Club Soda",3,"oz",false]]),
 recipe("grapefruit-fizz-mocktail","Grapefruit Fizz","mocktail","Grapefruit and soda with light sweetness.","Build grapefruit juice and syrup over ice, top with club soda, and stir.","Virtual Bartender curated mocktail",L,[["Grapefruit Juice",3,"oz",false],["Simple Syrup",0.5,"oz",false],["Club Soda",3,"oz",false]]),
 ...[["lemon-soda-mocktail","Lemon Soda","Lemon Juice"],["lime-soda-mocktail","Lime Soda","Lime Juice"]].map(([k,n,j])=>recipe(k,n,"mocktail",`A simple sparkling ${j.toLowerCase()} cooler.`,`Build ${j.toLowerCase()} and syrup over ice, top with club soda, and stir.`,"Virtual Bartender curated mocktail",L,[[j,1,"oz",false],["Simple Syrup",0.75,"oz",false],["Club Soda",4,"oz",false]])),
 ...[["pineapple-ginger-mocktail","Pineapple Ginger","Pineapple Juice"],["cranberry-ginger-mocktail","Cranberry Ginger","Cranberry Juice"],["orange-ginger-mocktail","Orange Ginger","Orange Juice"]].map(([k,n,j])=>recipe(k,n,"mocktail",`${j} with ginger ale.`,`Build ${j.toLowerCase()} over ice, top with ginger ale, and stir.`,"Virtual Bartender curated mocktail",L,[[j,3,"oz",false],["Ginger Ale",3,"oz",false]])),
 recipe("grapefruit-tonic-mocktail","Grapefruit Tonic","mocktail","Grapefruit juice with tonic water.","Build grapefruit juice over ice, top with tonic, and stir.","Virtual Bartender curated mocktail",L,[["Grapefruit Juice",2,"oz",false],["Tonic Water",4,"oz",false]]),
 ...[["lime-tonic-mocktail","Lime Tonic","Lime Juice"],["lemon-tonic-mocktail","Lemon Tonic","Lemon Juice"]].map(([k,n,j])=>recipe(k,n,"mocktail",`${j} and tonic water over ice.`,`Build ${j.toLowerCase()} over ice, top with tonic, and stir.`,"Virtual Bartender curated mocktail",L,[[j,0.75,"oz",false],["Tonic Water",4,"oz",false]]))
];
