import { recipe } from "./catalogHelpers";

export const RECIPES_V3 = [
  recipe("vodka-tonic","Vodka Tonic","cocktail","A simple vodka highball with tonic.","Build vodka and tonic water over ice and stir gently.","Virtual Bartender curated highball","local://virtual-bartender/curated",[["Vodka",2,"oz",false],["Tonic Water",4,"oz",false],["Lime Wedge",1,"pc",true]]),
  recipe("rum-cola","Rum and Cola","cocktail","A straightforward rum and cola highball.","Build rum and cola over ice and stir gently.","Virtual Bartender curated highball","local://virtual-bartender/curated",[["White Rum",2,"oz",false],["Cola",4,"oz",false]]),
  recipe("bourbon-cola","Bourbon and Cola","cocktail","Bourbon topped with cola.","Build bourbon and cola over ice and stir gently.","Virtual Bartender curated highball","local://virtual-bartender/curated",[["Bourbon",2,"oz",false],["Cola",4,"oz",false]]),
  recipe("scotch-soda","Scotch and Soda","cocktail","Scotch lengthened with soda water.","Build Scotch over ice, top with club soda, and stir gently.","Virtual Bartender curated highball","local://virtual-bartender/curated",[["Scotch Whisky",2,"oz",false],["Club Soda",4,"oz",false]]),
  recipe("gin-rickey","Gin Rickey","cocktail","A dry gin highball with lime and soda.","Build gin and lime over ice, top with club soda, and stir.","Classic reference","https://en.wikibooks.org/wiki/Bartending/Cocktails",[["Gin",2,"oz",false],["Lime Juice",0.75,"oz",false],["Club Soda",4,"oz",false]]),
  recipe("greyhound","Greyhound","cocktail","Vodka and grapefruit juice over ice.","Build vodka and grapefruit juice over ice and stir.","Classic reference","https://en.wikibooks.org/wiki/Bartending/Cocktails",[["Vodka",2,"oz",false],["Grapefruit Juice",4,"oz",false]]),
  recipe("cape-codder","Cape Codder","cocktail","Vodka and cranberry juice with an optional lime garnish.","Build vodka and cranberry juice over ice and stir gently.","Classic reference","https://en.wikibooks.org/wiki/Bartending/Cocktails",[["Vodka",2,"oz",false],["Cranberry Juice",4,"oz",false],["Lime Wedge",1,"pc",true]]),
  recipe("screwdriver","Screwdriver","cocktail","Vodka and orange juice.","Build vodka and orange juice over ice and stir.","Classic reference","https://en.wikibooks.org/wiki/Bartending/Cocktails",[["Vodka",2,"oz",false],["Orange Juice",4,"oz",false]]),
  recipe("salty-dog","Salty Dog","cocktail","A salted-rim grapefruit and vodka highball.","Salt the rim if desired, then build vodka and grapefruit juice over ice.","Classic reference","https://en.wikibooks.org/wiki/Bartending/Cocktails",[["Vodka",2,"oz",false],["Grapefruit Juice",4,"oz",false],["Salt",1,"tsp",true]]),
  recipe("rum-punch","Rum Punch","cocktail","A fruity rum punch with citrus and pineapple.","Shake rum and juices with ice, strain over fresh ice, and add grenadine.","Virtual Bartender curated punch","local://virtual-bartender/curated",[["Dark Rum",1.5,"oz",false],["White Rum",1,"oz",false],["Orange Juice",1.5,"oz",false],["Pineapple Juice",1.5,"oz",false],["Lime Juice",0.5,"oz",false],["Grenadine",0.25,"oz",false]]),
  recipe("planters-punch","Planter's Punch","cocktail","A rum punch with citrus, sugar, and bitters.","Shake rum, lime, syrup, and bitters with ice and strain over fresh ice.","IBA reference","https://iba-world.com/cocktails/",[["Dark Rum",2,"oz",false],["Lime Juice",1,"oz",false],["Simple Syrup",0.75,"oz",false],["Angostura Bitters",3,"dash",false]]),
  recipe("amaretto-sour","Amaretto Sour","cocktail","A sweet-tart amaretto sour.","Shake amaretto, lemon, and syrup with ice and strain over fresh ice.","Virtual Bartender curated classic","local://virtual-bartender/curated",[["Amaretto",2,"oz",false],["Lemon Juice",1,"oz",false],["Simple Syrup",0.5,"oz",false]]),
  recipe("bramble","Bramble","cocktail","A gin sour with berry sweetness.","Shake gin, lemon, and syrup with ice, strain over crushed ice, and finish with raspberry syrup.","IBA reference","https://iba-world.com/cocktails/",[["Gin",2,"oz",false],["Lemon Juice",1,"oz",false],["Simple Syrup",0.5,"oz",false],["Raspberry Syrup",0.5,"oz",false]]),
  recipe("southside","Southside","cocktail","A minty gin sour.","Shake gin, lime, syrup, and mint with ice, then strain into a chilled glass.","Classic reference","https://en.wikibooks.org/wiki/Bartending/Cocktails",[["Gin",2,"oz",false],["Lime Juice",0.75,"oz",false],["Simple Syrup",0.75,"oz",false],["Mint Leaves",6,"pc",false]]),
  recipe("gold-rush","Gold Rush","cocktail","A bourbon sour sweetened with honey.","Shake bourbon, lemon, and honey syrup with ice and strain over fresh ice.","Virtual Bartender curated modern classic","local://virtual-bartender/curated",[["Bourbon",2,"oz",false],["Lemon Juice",0.75,"oz",false],["Honey Syrup",0.75,"oz",false]]),
  recipe("penicillin","Penicillin","cocktail","A smoky Scotch sour with honey and ginger character.","Shake Scotch, lemon, and honey syrup with ice and strain over fresh ice.","Virtual Bartender curated modern classic","local://virtual-bartender/curated",[["Scotch Whisky",2,"oz",false],["Lemon Juice",0.75,"oz",false],["Honey Syrup",0.75,"oz",false],["Ginger Beer",0.5,"oz",true]]),
  recipe("paper-plane","Paper Plane","cocktail","A bittersweet bourbon sour built in equal parts.","Shake bourbon, Aperol, amaretto, and lemon juice with ice and strain into a chilled glass.","Virtual Bartender curated modern classic","local://virtual-bartender/curated",[["Bourbon",0.75,"oz",false],["Aperol",0.75,"oz",false],["Amaretto",0.75,"oz",false],["Lemon Juice",0.75,"oz",false]]),
  recipe("mocktail-sunrise","Sunrise Mocktail","mocktail","Orange juice and grenadine with a soda finish.","Build orange juice over ice, add grenadine slowly, and top with club soda.","Virtual Bartender curated mocktail","local://virtual-bartender/curated",[["Orange Juice",4,"oz",false],["Grenadine",0.5,"oz",false],["Club Soda",2,"oz",false]]),
  recipe("pineapple-fizz","Pineapple Fizz","mocktail","A pineapple and lime sparkling mocktail.","Shake pineapple and lime with ice, strain over fresh ice, and top with club soda.","Virtual Bartender curated mocktail","local://virtual-bartender/curated",[["Pineapple Juice",3,"oz",false],["Lime Juice",0.75,"oz",false],["Simple Syrup",0.5,"oz",false],["Club Soda",2,"oz",false]]),
  recipe("cranberry-lime-spritz","Cranberry Lime Spritz","mocktail","A tart cranberry and lime spritz.","Build cranberry and lime over ice, top with club soda, and stir.","Virtual Bartender curated mocktail","local://virtual-bartender/curated",[["Cranberry Juice",3,"oz",false],["Lime Juice",0.75,"oz",false],["Club Soda",3,"oz",false]])
];
