import { useState } from "react";
import { createCustomRecipe, ingredientFromName, saveCustomRecipe } from "../storage/customRecipes";
import type { RecipeIngredient } from "../catalog/recipes";

type Props = { onHome: () => void; onBack: () => void; openRecipe: (key: string) => void };
type IngredientDraft = { quantity: string; unit: string; name: string };

export default function RecipeManagePage({ onHome, onBack, openRecipe }: Props) {
  const [name,setName]=useState(""); const [type,setType]=useState<"cocktail"|"mocktail">("cocktail"); const [description,setDescription]=useState(""); const [instructions,setInstructions]=useState(""); const [source,setSource]=useState(""); const [sourceUrl,setSourceUrl]=useState("");
  const [ingredients,setIngredients]=useState<IngredientDraft[]>([{quantity:"1",unit:"oz",name:""}]); const [savedKey,setSavedKey]=useState<string|null>(null); const [error,setError]=useState("");
  function updateIngredient(index:number,key:keyof IngredientDraft,value:string){setIngredients(current=>current.map((item,i)=>i===index?{...item,[key]:value}:item));}
  function addIngredient(){setIngredients(current=>[...current,{quantity:"1",unit:"oz",name:""}]);}
  function removeIngredient(index:number){setIngredients(current=>current.filter((_,i)=>i!==index));}
  function save(){setError(""); const valid=ingredients.filter(i=>i.name.trim()); if(!name.trim()||valid.length===0){setError("Enter a recipe name and at least one ingredient.");return;} const recipeIngredients:RecipeIngredient[]=valid.map(i=>ingredientFromName(i.name,Number(i.quantity)||1,i.unit||"pc")); const recipe=createCustomRecipe({name,type,description,instructions,source,sourceUrl,ingredients:recipeIngredients}); saveCustomRecipe(recipe); setSavedKey(recipe.key);}
  return <main className="page theme-recipes"><header className="app-header"><button className="back-button" onClick={onHome}>← Home</button><button className="back-button" onClick={onBack}>← Recipes</button><div className="page-heading"><span className="page-heading-icon">📖</span><h1>Add / Import Recipe</h1></div></header><div className="theme-prop recipe-ledger"><strong>Recipe Desk</strong><span>Add your own formula or bring in recipe details you want to keep locally.</span></div><p className="lede">Recipes saved here stay in this browser. Website scraping is not guaranteed in a browser-only edition because recipe sites may block direct browser access.</p><section className="detail-card"><label>Recipe name<input className="wide-input" value={name} onChange={e=>setName(e.target.value)} placeholder="Recipe name"/></label><label> Type <select value={type} onChange={e=>setType(e.target.value as "cocktail"|"mocktail")}><option value="cocktail">Cocktail</option><option value="mocktail">Mocktail</option></select></label><label>Description<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Source<input className="wide-input" value={source} onChange={e=>setSource(e.target.value)} placeholder="Optional source name"/></label><label>Source URL<input className="wide-input" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Optional https://..."/></label><h3>Ingredients</h3><div className="import-ingredients">{ingredients.map((item,index)=><div className="import-row" key={index}><input value={item.quantity} onChange={e=>updateIngredient(index,"quantity",e.target.value)} placeholder="Qty"/><select value={item.unit} onChange={e=>updateIngredient(index,"unit",e.target.value)}><option value="oz">oz</option><option value="tsp">tsp</option><option value="tbsp">tbsp</option><option value="dash">dash</option><option value="pc">pc</option><option value="ml">ml</option></select><input value={item.name} onChange={e=>updateIngredient(index,"name",e.target.value)} placeholder="Ingredient"/><button className="danger-link" onClick={()=>removeIngredient(index)}>Remove</button></div>)}</div><button onClick={addIngredient}>+ Ingredient</button><h3>Instructions</h3><textarea rows={8} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Mixing instructions"/><div className="toolbar"><button className="primary" onClick={save}>Save Recipe</button></div>{error&&<p className="error">{error}</p>}{savedKey&&<p className="success">Recipe saved successfully. <button className="link-button" onClick={()=>openRecipe(savedKey)}>View Recipe</button></p>}</section></main>;
}
