import { useMemo,useState } from "react";
import { BUILTIN_RECIPES } from "../catalog/catalog";
import { deleteCustomRecipe,getCustomRecipe,saveCustomRecipe } from "../storage/customRecipes";
import { addHistory,applyRecipeOverride,hideRecipe,isFavorite,saveRecipeOverride,setFavorite } from "../storage/recipeUserData";

type Props={recipeKey:string;onHome:()=>void;onBack:()=>void};
function metricAmount(q:number,u:string){if(u==="oz")return `${Math.round(q*29.5735)} ml`;if(u==="tsp")return `${Math.round(q*4.92892)} ml`;if(u==="tbsp")return `${Math.round(q*14.7868)} ml`;return `${q} ${u}`;}
export default function RecipeDetailPage({recipeKey,onHome,onBack}:Props){
 const builtIn=BUILTIN_RECIPES.find(r=>r.key===recipeKey);const custom=getCustomRecipe(recipeKey);const initial=builtIn?applyRecipeOverride(builtIn):custom;const [metric,setMetric]=useState(false);const [favorite,setFav]=useState(isFavorite(recipeKey));const [rating,setRating]=useState("5");const [notes,setNotes]=useState("");const [editing,setEditing]=useState(false);const [edit,setEdit]=useState({name:initial?.name||"",description:initial?.description||"",type:initial?.type||"cocktail" as "cocktail"|"mocktail",instructions:initial?.instructions||""});const [version,setVersion]=useState(0);
 const recipe=useMemo(()=>builtIn?applyRecipeOverride(builtIn):getCustomRecipe(recipeKey),[builtIn,recipeKey,version]);if(!recipe)return <main className="page"><p>Recipe not found.</p><button onClick={onBack}>Back</button></main>;
 function toggleFavorite(){const next=!favorite;setFavorite(recipe.key,next);setFav(next)}
 function madeThis(){addHistory({recipeKey:recipe.key,recipeName:recipe.name,rating:Number(rating),notes:notes||undefined});setNotes("");window.alert("Added to drink history.")}
 function saveEdit(){if(builtIn)saveRecipeOverride(recipe.key,edit);else saveCustomRecipe({...recipe,...edit});setEditing(false);setVersion(v=>v+1)}
 function remove(){const message=builtIn?"Hide this built-in recipe from your local catalog?":"Delete this user-added recipe? This cannot be undone.";if(!window.confirm(message))return;if(builtIn)hideRecipe(recipe.key);else deleteCustomRecipe(recipe.key);onBack()}
 return <main className="page"><header className="app-header"><button className="back-button" onClick={onHome}>← Home</button><button className="back-button" onClick={onBack}>← Recipes</button><div className="page-heading"><h1>{recipe.name}</h1></div></header><h1 className="recipe-print-title print-only">{recipe.name}</h1><div className="toolbar no-print"><button className="primary" onClick={()=>setEditing(!editing)}>✎ Edit</button><button onClick={toggleFavorite}>{favorite?"★ Favorite":"☆ Add Favorite"}</button><button onClick={()=>setMetric(!metric)}>{metric?"US Units":"Metric"}</button><button onClick={()=>window.print()}>Print Recipe</button><button className="danger-link" onClick={remove}>{builtIn?"Hide Recipe":"Delete Recipe"}</button></div>{editing&&<section className="detail-card no-print"><p className="eyebrow">Local recipe edit</p><p className="lede">This changes your local browser copy.</p><label>Name<input className="wide-input" value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Description<textarea rows={3} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><label>Type <select value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value as "cocktail"|"mocktail"})}><option value="cocktail">Cocktail</option><option value="mocktail">Mocktail</option></select></label><label>Instructions<textarea rows={8} value={edit.instructions} onChange={e=>setEdit({...edit,instructions:e.target.value})}/></label><div className="toolbar"><button className="primary" onClick={saveEdit}>Save Changes</button><button onClick={()=>setEditing(false)}>Cancel</button></div></section>}{recipe.description&&<p className="lede">{recipe.description}</p>}<section className="detail-card"><h2>Ingredients</h2><ul>{recipe.ingredients.map(i=><li key={`${recipe.key}-${i.ingredientId}`}>{metric?metricAmount(i.quantity,i.unit):`${i.quantity} ${i.unit}`} {i.ingredientName}{i.optional?" (optional)":""}</li>)}</ul></section><section className="detail-card"><h2>Instructions</h2><p>{recipe.instructions||"No instructions yet."}</p></section><section className="detail-card no-print"><h2>I Made This</h2><label>Rating <select value={rating} onChange={e=>setRating(e.target.value)}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} star{n===1?"":"s"}</option>)}</select></label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional notes" rows={4}/><button className="primary" onClick={madeThis}>Confirm Made</button></section></main>;
}
