import { useRef,useState } from "react";
import { createBrowserBackup,downloadBackup,restoreBrowserBackup,type BrowserBackup } from "../storage/backupData";

type Props={onHome:()=>void};
export default function SettingsPage({onHome}:Props){
 const [message,setMessage]=useState("");const input=useRef<HTMLInputElement>(null);
 async function backup(){setMessage("Creating backup…");try{const data=await createBrowserBackup();downloadBackup(data);setMessage("Backup downloaded. Keep this file somewhere safe.");}catch(err){setMessage(err instanceof Error?err.message:"Backup failed.");}}
 async function restore(file:File){setMessage("");try{const data=JSON.parse(await file.text()) as BrowserBackup;if(!window.confirm("Restore this backup? Your existing Virtual Bartender browser data will be replaced. This cannot be merged."))return;await restoreBrowserBackup(data);setMessage("Backup restored. Reload Virtual Bartender before continuing.");}catch(err){setMessage(err instanceof Error?err.message:"Restore failed.");}finally{if(input.current)input.current.value="";}}
 return <main className="page"><header className="app-header"><button className="back-button" onClick={onHome}>← Home</button><div className="page-heading"><span className="page-heading-icon">⚙</span><h1>Admin / Settings</h1></div></header><section className="detail-card"><h2>Backup & Restore</h2><p className="lede">This Web edition stores your personal Virtual Bartender data in this browser. Export a backup file to protect it or move it to another browser/computer.</p><div className="toolbar"><button className="primary" onClick={()=>void backup()}>Export Full Backup</button><button onClick={()=>input.current?.click()}>Import / Restore Backup</button><input ref={input} type="file" accept="application/json,.json" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void restore(file);}}/></div><p><strong>Restore replaces existing data.</strong> There is no merge option.</p>{message&&<p>{message}</p>}</section><section className="detail-card"><h2>What the backup contains</h2><p>My Bar, Tonight's Bar sessions, custom recipes, favorites, recipe edits/hidden recipes, shopping list and drink history.</p><p>The built-in recipe and ingredient catalogs remain part of the application and do not need to be copied into the backup.</p></section></main>;
}
