#!/usr/bin/env python3
"""Generate the browser-native Virtual Bartender catalog from canonical sources.

This tool intentionally treats the existing Virtual Bartender Python catalog as
canonical. It downloads the source files, parses only literal assignments via
Python's AST, validates the combined catalog, and emits a TypeScript file.
"""

from __future__ import annotations

import argparse
import ast
import json
import pathlib
import urllib.request
from collections import Counter
from typing import Any

BASE = "https://raw.githubusercontent.com/rpiammocan/virtual-bartender-casaos/main/backend/app"
SOURCES = [
    ("seed.py", None),
    ("catalog_v2.py", "RECIPES_V2"),
    ("catalog_v3.py", "RECIPES_V3"),
    ("catalog_v4.py", "RECIPES_V4"),
    ("catalog_v5.py", "RECIPES_V5"),
    ("catalog_v6.py", "RECIPES_V6"),
    ("catalog_v7.py", "RECIPES_V7"),
]


def fetch_text(name: str) -> str:
    with urllib.request.urlopen(f"{BASE}/{name}", timeout=30) as response:
        return response.read().decode("utf-8")


def literal_assignments(source: str) -> dict[str, Any]:
    tree = ast.parse(source)
    values: dict[str, Any] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name):
            continue
        try:
            values[target.id] = ast.literal_eval(node.value)
        except (ValueError, TypeError):
            continue
    return values


def find_base_recipes(assignments: dict[str, Any]) -> list[dict[str, Any]]:
    candidates: list[tuple[str, list[dict[str, Any]]]] = []
    for name, value in assignments.items():
        if not isinstance(value, list) or not value:
            continue
        if not all(isinstance(item, dict) for item in value):
            continue
        if not all("key" in item and "ingredients" in item for item in value):
            continue
        candidates.append((name, value))
    if not candidates:
        raise RuntimeError("Could not locate base recipe list in seed.py")
    candidates.sort(key=lambda pair: ("recipe" not in pair[0].lower(), -len(pair[1])))
    return candidates[0][1]


def normalize_recipe(raw: dict[str, Any]) -> dict[str, Any]:
    ingredients = []
    for name, quantity, unit, optional in raw["ingredients"]:
        ingredients.append({
            "ingredientName": name,
            "quantity": quantity,
            "unit": unit,
            "optional": bool(optional),
        })
    return {
        "key": raw["key"],
        "name": raw["name"],
        "type": raw.get("type", "cocktail"),
        "version": raw.get("version", "1.0"),
        "description": raw.get("description", ""),
        "instructions": raw.get("instructions", ""),
        "source": raw.get("source", ""),
        "sourceUrl": raw.get("url", ""),
        "parentKey": raw.get("parent"),
        "ingredients": ingredients,
    }


def load_catalog() -> list[dict[str, Any]]:
    combined: list[dict[str, Any]] = []
    for filename, variable in SOURCES:
        assignments = literal_assignments(fetch_text(filename))
        recipes = assignments[variable] if variable else find_base_recipes(assignments)
        combined.extend(normalize_recipe(recipe) for recipe in recipes)
    return combined


def validate(recipes: list[dict[str, Any]]) -> None:
    keys = [recipe["key"] for recipe in recipes]
    duplicates = sorted(key for key, count in Counter(keys).items() if count > 1)
    if duplicates:
        raise RuntimeError(f"Duplicate recipe keys: {', '.join(duplicates)}")

    key_set = set(keys)
    missing_parents = sorted({
        recipe["parentKey"]
        for recipe in recipes
        if recipe.get("parentKey") and recipe["parentKey"] not in key_set
    })
    if missing_parents:
        raise RuntimeError(f"Missing parent recipes: {', '.join(missing_parents)}")

    for recipe in recipes:
        if not recipe["ingredients"]:
            raise RuntimeError(f"Recipe has no ingredients: {recipe['key']}")
        for ingredient in recipe["ingredients"]:
            if not ingredient["ingredientName"]:
                raise RuntimeError(f"Blank ingredient in recipe: {recipe['key']}")


def ts_string(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def emit_typescript(recipes: list[dict[str, Any]]) -> str:
    payload = json.dumps(recipes, ensure_ascii=False, indent=2)
    return (
        "// AUTO-GENERATED by tools/generate_catalog.py. DO NOT EDIT BY HAND.\n"
        "import type { CatalogRecipe } from './recipes';\n"
        "import { ingredientId } from './catalogHelpers';\n\n"
        f"const RAW = {payload} as const;\n\n"
        "export const BUILTIN_RECIPES: CatalogRecipe[] = RAW.map((recipe) => ({\n"
        "  ...recipe,\n"
        "  parentKey: recipe.parentKey ?? undefined,\n"
        "  ingredients: recipe.ingredients.map((item) => ({\n"
        "    ...item,\n"
        "    ingredientId: ingredientId(item.ingredientName),\n"
        "  })),\n"
        "}));\n\n"
        "export const BUILTIN_RECIPES_BY_KEY = new Map(\n"
        "  BUILTIN_RECIPES.map((recipe) => [recipe.key, recipe]),\n"
        ");\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default="src/catalog/generatedCatalog.ts",
        help="TypeScript output path",
    )
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()

    recipes = load_catalog()
    validate(recipes)
    cocktails = sum(recipe["type"] == "cocktail" for recipe in recipes)
    mocktails = sum(recipe["type"] == "mocktail" for recipe in recipes)
    print(f"Validated {len(recipes)} recipes: {cocktails} cocktails, {mocktails} mocktails")

    if not args.check_only:
        output = pathlib.Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(emit_typescript(recipes), encoding="utf-8")
        print(f"Wrote {output}")


if __name__ == "__main__":
    main()
